UrlBundle\Entity\User:
  type: entity
  table: user
  repositoryClass: UrlBundle\Entity\LinkRepository 
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    name:
      type: string
      length: 255
    email:
      type: string
      length: 255
      unique: true  
  oneToMany:
    links:
      targetEntity: Link
      mappedBy: user